include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # avoid_print: false  # Uncomment to disable the `avoid_print` rule
     prefer_single_quotes: true
     prefer_relative_imports: true
     prefer_final_fields: true
     use_super_parameters: true
