name: pluto
description: A beautiful new tab for your browser built with love in Flutter.

publish_to: 'none'

version: 0.3.0

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  shared_preferences: ^2.0.15
  provider: ^6.0.5
  get_it: ^7.2.0
  json_annotation: ^4.7.0
  collection: ^1.17.0
  intl: ^0.18.0
  http: ^0.13.5
#  dropdown_button2: ^1.9.2
  file_picker: ^5.2.4
  screwdriver: ^3.1.1
  flutter_multi_formatter: ^2.9.14
  url_launcher: ^6.1.7
#  package_info_plus: ^3.0.2
  flutter_screwdriver: ^2.1.0
  flutter_markdown: ^0.6.13
  mobx: ^2.1.3
  flutter_mobx: ^2.0.6+5
  rxdart: ^0.27.7

dependency_overrides:
  collection: ^1.17.0
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  characters: ^1.2.1
  dart_style: ^2.2.4
  json_serializable: ^6.5.4
  flutter_launcher_icons: ^0.11.0
  yaml: ^3.1.1
  mobx_codegen: ^2.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/

  fonts:
    - family: Product
      fonts:
        - asset: assets/fonts/Product.ttf
    - family: Cardo
      fonts:
        - asset: assets/fonts/Cardo-Regular.ttf
    - family: Cardo Italics
      fonts:
        - asset: assets/fonts/Cardo-Italics.ttf
    - family: Jakarta Sans
      fonts:
        - asset: assets/fonts/JakartaSans-Regular.ttf
        - asset: assets/fonts/JakartaSans-Medium.ttf
          weight: 500
    - family: Renner
      fonts:
        - asset: assets/fonts/Renner-Medium.otf

scripts: derry.yaml