name: minima
description: A minimal new tab for Chrome.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  shared_preferences: ^2.0.15
  provider: ^6.0.4
  get_it: ^7.2.0
  json_annotation: ^4.7.0
  collection: ^1.16.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.2
  flutter_lints: ^2.0.1
  characters: ^1.2.1
  dart_style: ^2.2.4
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/

  fonts:
    - family: Product
      fonts:
        - asset: assets/fonts/Product.ttf
    - family: Cardo
      fonts:
        - asset: assets/fonts/Cardo-Regular.ttf
    - family: Cardo Italics
      fonts:
        - asset: assets/fonts/Cardo-Italics.ttf
#          style: italic
    - family: Jakarta Sans
      fonts:
        - asset: assets/fonts/JakartaSans-Regular.ttf
        - asset: assets/fonts/JakartaSans-Medium.ttf
          weight: 500
    - family: Renner
      fonts:
        - asset: assets/fonts/Renner-Medium.otf

scripts:
  build: flutter build web --release --web-renderer html --csp
  generate_colors: dart scripts/generators/colors_generator.dart scripts/generators/colors.json lib/resources/flat_colors.dart
  generate_gradients: dart scripts/generators/gradients_generator.dart scripts/generators/colors.json lib/resources/color_gradients.dart