name: pluto
description: A beautiful new tab for your browser built with love in Flutter.

publish_to: 'none'

version: 0.4.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  shared_preferences: ^2.2.0
  provider: ^6.0.5
  get_it: ^7.6.0
  json_annotation: ^4.8.1
  collection: ^1.17.1
  intl: ^0.18.1
  http: ^1.1.0
#  dropdown_button2: ^1.9.2
  file_picker: ^5.3.2
  screwdriver: ^5.2.0
  flutter_multi_formatter: ^2.11.1
  url_launcher: ^6.1.11
#  package_info_plus: ^3.0.2
  flutter_screwdriver: ^3.0.0
  flutter_markdown: ^0.6.15+1
  mobx: ^2.2.0
  flutter_mobx: ^2.0.6+5
  rxdart: ^0.27.7
  universal_html: ^2.2.3
  universal_io: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  flutter_lints: ^2.0.2
  characters: ^1.3.0
  dart_style: ^2.3.2
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.13.1
  yaml: ^3.1.2
  mobx_codegen: ^2.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/

  fonts:
    - family: Product
      fonts:
        - asset: assets/fonts/Product.ttf
    - family: Cardo
      fonts:
        - asset: assets/fonts/Cardo-Regular.ttf
    - family: Cardo Italics
      fonts:
        - asset: assets/fonts/Cardo-Italics.ttf
    - family: Jakarta Sans
      fonts:
        - asset: assets/fonts/JakartaSans-Regular.ttf
        - asset: assets/fonts/JakartaSans-Medium.ttf
          weight: 500
    - family: Renner
      fonts:
        - asset: assets/fonts/Renner-Medium.otf

scripts: scripts.yaml