name: pluto
description: A beautiful new tab for your browser built with love in Flutter.

publish_to: 'none'

version: 0.6.1

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.22.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  shared_preferences: ^2.3.3
  provider: ^6.1.2
  get_it: ^8.0.2
  json_annotation: ^4.9.0
  collection: ^1.19.0
  intl: ^0.19.0
  http: ^1.2.2
#  dropdown_button2: ^1.9.2
  file_picker: ^8.1.4
  screwdriver: ^5.8.0
  flutter_multi_formatter: ^2.13.0
  url_launcher: ^6.3.1
  package_info_plus: ^8.1.1
  flutter_screwdriver: ^3.2.0
  flutter_markdown: ^0.7.4+1
  mobx: ^2.4.0
  flutter_mobx: ^2.2.1+1
  rxdart: ^0.28.0
  universal_html: ^2.2.4
  universal_io: ^2.2.2
  unsplash_client: ^2.2.0
  shared:
    path: shared

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0
  characters: ^1.3.0
  dart_style: ^2.3.7
  json_serializable: ^6.8.0
  flutter_launcher_icons: ^0.14.1
  yaml: ^3.1.2
  mobx_codegen: ^2.6.2

dependency_overrides:
  watcher: ^1.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/

  fonts:
    - family: Product
      fonts:
        - asset: assets/fonts/Product.ttf
    - family: Cardo
      fonts:
        - asset: assets/fonts/Cardo-Regular.ttf
    - family: Cardo Italics
      fonts:
        - asset: assets/fonts/Cardo-Italics.ttf
    - family: Jakarta Sans
      fonts:
        - asset: assets/fonts/JakartaSans-Regular.ttf
        - asset: assets/fonts/JakartaSans-Medium.ttf
          weight: 500
    - family: Renner
      fonts:
        - asset: assets/fonts/Renner-Medium.otf

scripts: scripts.yaml