name: celest_backend
description: The Celest backend for pluto.
publish_to: none

environment:
  sdk: ^3.3.0

dependencies:
  celest: ^0.4.0
  http: ^1.2.1
  unsplash_client: ^2.2.0
  equatable: ^2.0.5
  json_annotation: ^4.9.0
  shared:
    path: ../shared

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
celest:
  project:
    id: project_01j0x6kg0qf2magf641vbe0p5y
