name: server
description: A server app using the shelf package and Docker.
version: 1.0.0

publish_to: none

# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  http: ^1.2.2
  unsplash_client: ^2.2.0
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  shared:
    path: ../shared
  dotenv: ^4.2.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.12
  build_runner: ^2.4.14
  json_serializable: ^6.9.0
