name: shared

publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  equatable: ^2.0.7
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.14
  json_serializable: ^6.9.0