name: shared

publish_to: none

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  equatable: ^2.0.5
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.13
  json_serializable: ^6.8.0