name: Artifacts

on:
  release:
    types: [ published ]
  workflow_dispatch:
    branches: [ main ]

jobs:
  publish_artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: beta
      - run: flutter --version
      - name: Install dependencies
        run: flutter pub get
      - name: Update version
        run: dart scripts/update_version.dart
      - name: Build
        run: flutter build web --release --web-renderer=canvaskit --csp --no-web-resources-cdn
      - name: Add LICENSE
        run: cp LICENSE build/web
      - name: Install ZIP tool
        run: sudo apt-get install zip
      - name: Archive
        run: |
          cd build
          mkdir artifact
          zip -r artifact/pluto-v${{ github.event.release.tag_name }}.zip web
          cd ..
      - name: Upload artifacts to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/artifact/*
          tag: ${{ github.ref }}
          file_glob: true