name: Publish

on:
  release:
    types: [ published ]
  workflow_dispatch:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter --version
      - name: Install dependencies
        run: flutter pub get
      - name: Update version
        run: dart scripts/update_version.dart
      - name: Build
        run: flutter build web --release --web-renderer html --csp
      - name: Add LICENSE
        run: cp LICENSE build/web
      - name: Install ZIP tool
        run: sudo apt-get install zip
      - name: Archive
        run: |
          cd build
          zip -r extension.zip web
          cd ..
      - name: Chrome Extension upload & publish
        uses: Passiverecords/chrome-extension-upload-action@1.4.1
        with:
          refresh-token: ${{ secrets.REFRESH_TOKEN }}
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          file-name: build/extension.zip
          app-id: ${{ secrets.APP_ID }}
          publish: true